### ISSUE TITLE
Version update?

### ISSUE THREAD

**Issue by pat-s** [jchonig/docker-monit#1]
Hi,

thanks for the monit-related images.
I am wondering if you plan to conduct any maintenance/version updates to the docker image in the future or if one should fork this repo and build a new image?

This applies to 

- `monit`
- `m/monit`
- `monit-docker`

**Comment by jchonig** [comment]
I manually update when there are new releases of Monit or M/Monit.

It's supposed to automatically rebuild when the upstream base image updates.

The docker-monit image is based on lsiobase/alpine:latest.  That tag is not maintained, so I need to specify an alpine version 3.11 or 3.12.  I don't currently use this image regularly, the project I created it for is stalled.  So I won't be testing it directly.

I do use the M/Monit container.  That is based on lsisobase/ubuntu.  I'm not sure about the `latest` take there, I'll probably change that to focal.  I do run this image regularly.

**Comment by pat-s** [comment]
Thanks or the quickl reply.

The current `monit` version one gets when using the `jchonig/monit` docker image is 5.25.2 (May 2018) which is somewhat outdated (current release = 5.27.1). This might be due to the library version within Alpine 3.11 I assume?

For `m/monit` it is 3.7.4 with the current release being 3.7.6.

I am aware that I can just fork and rebuild myself using the latest versions - just wanted to know if I should do so or if you're actively on it :) 

On a sidenote: I am somewhat new to monit and wondering how you can use `mmonit` without `monit`? AFAIK `monit` is the client which reports to the `mmonit` instance? (We have a `mmonit` running only since yesterday with 1 host so I might be missing something).

**Comment by jchonig** [comment]
Ah, that version.

Alpine is based on busybox.  The pre-compiled official monit binaries will not run there because they were compiled with glibc and some symbols are missing.  The only options are to use the alpine version (5.25.2), or compile a new version from source.

I'll upgrade this container to lsisobase/alpine:3.12 which will bring monit up to 5.26.0.

The M/Monit container is currently based on 3.7.6 and will automatically upgrade on start if you specify MMONIT_VERSION.  The maintainers of M/Monit remove previous versions when they release a new one

**Comment by pat-s** [comment]
> Alpine is based on busybox. The pre-compiled official monit binaries will not run there because they were compiled with glibc and some symbols are missing. The only options are to use the alpine version (5.25.2), or compile a new version from source.
I'll upgrade this container to lsisobase/alpine:3.12 which will bring monit up to 5.26.0.

Thanks, that's what I meant :)
I am not familiar with Alpine release cycles - looks like that the latest binaries are roughly a year behind, is that correct?

> The M/Monit container is currently based on 3.7.6 and will automatically upgrade on start if you specify MMONIT_VERSION. The maintainers of M/Monit remove previous versions when they release a new one

Whenever I specify a version (e.g. `MMONIT_VERSION-3.7.6`) the container fails to start as all config files cannot be found. Without a version I get v3.7.4 and everything just works.

**Comment by jchonig** [comment]
Actually, it's not busybox that's the issue, it's musl C library.

What version are you specifying for the jchonig/mmonit container?

Can you provide some logs of what's happening?

**Comment by pat-s** [comment]
> What version are you specifying for the jchonig/mmonit container?

3.7.6

As mentioned, without a version startup is just fine and I get 3.7.4

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 45-upgrade: exited 0.
[cont-init.d] 50-config: executing... 
Environment:
    PUID=1000
    PGID=1000
    TZ=Europe/Zurich
    MMONIT_LIMIT_FD=4096
    MMONIT_VERSION=3.7.6

rsync: link_stat "/opt/mmonit-3.7.6" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
rm: cannot remove 'logs': Device or resource busy
Escaping & in XML
sed: can't read /config/mmonit-3.7.6/conf/server.xml: No such file or directory
Setting M/Monit license owner
failed to load external entity "/config/mmonit-3.7.6/conf/license.xml"
Setting M/Monit license key
failed to load external entity "/config/mmonit-3.7.6/conf/license.xml"
Setting database URL
failed to load external entity "/config/mmonit-3.7.6/conf/server.xml"
Unsetting TLS version
failed to load external entity "/config/mmonit-3.7.6/conf/server.xml"
failed to load external entity "/config/mmonit-3.7.6/conf/server.xml"
Restoring escaped & in XML
sed: can't read /config/mmonit-3.7.6/conf/server.xml: No such file or directory
sed: can't read /config/mmonit-3.7.6/conf/server.xml: No such file or directory
chown: cannot access '/opt/mmonit-3.7.6': No such file or directory
[cont-init.d] 50-config: exited 1.
[cont-init.d] done.
[services.d] starting services
s6-applyuidgid: fatal: unable to exec /config/mmonit-3.7.6/bin/mmonit: No such file or directory
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by jchonig** [comment]
`docker run --name monit --expose 8080 -v ${PWD}/config:/config jchonig/mmonit:3.7.6` works for me.

What does your `/config` dir look like?  What's in `/config/version`?

**Comment by pat-s** [comment]
I did not take a look at the tags before - I was using `latest` until now which is 4 months old as of today.

Using the `:3.7.6` works for me :) 👍

**Comment by jchonig** [comment]
Ah, that explains it.

I deleted the `latest` tag as it's no longer mantained.
